In [18]:
import cv2

In [19]:
import numpy as np

In [2]:
import numpy as np
import cv2

cap = cv2.VideoCapture(0)
while(True):
    # Capture frame-by-frame
    ret,frame = cap.read()
    cv2.rectangle(frame, (100, 100), (200, 200), [255, 0, 0], 2)
    # Display the resulting frame
    cv2.imshow('frame',frame)
    if cv2.waitKey(25) & 0xFF == ord('q'):
        break

# When everything done, release the capture
cap.release()
cv2.destroyAllWindows() 

In [1]:
import cv2 
import numpy as np
input = cv2.imread('C:\\Users\\hp\\Desktop\\elephant.jpg',1)
#print(input)
#data = open(r"‪C:\Users\hp\Desktop\elephant.jpg")

cv2.imshow('Test Elephant Image', input)
cv2.waitKey()
cv2.destroyAllWindows()

In [51]:
print(input.shape)

(519, 778, 3)


In [52]:
# Let's print each dimension of the image

print('Height of Image:', int(input.shape[0]), 'pixels')
print('Width of Image: ', int(input.shape[1]), 'pixels')

Height of Image: 519 pixels
Width of Image:  778 pixels


In [53]:

# Simply use 'imwrite' specificing the file name and the image to be saved
cv2.imwrite('output.jpg', input)
cv2.imwrite('output.png', input)


True

In [2]:
import numpy as np
import cv2

# We point OpenCV's CascadeClassifier function to where our 
# classifier (XML file format) is stored
face_classifier = cv2.CascadeClassifier('C:\\Users\\hp\\Desktop\\haarcascade_frontalface_default.xml')

# Load our image then convert it to grayscale
image = cv2.imread('C:\\Users\\hp\\Desktop\\Modi.jpg',1)
gray = cv2.cvtColor(image , cv2.COLOR_RGB2GRAY)
#print(image)
# Our classifier returns the ROI of the detected face as a tuple
# It stores the top left coordinate and the bottom right coordiantes
faces = face_classifier.detectMultiScale(gray, 1.3, 5)

# When no faces detected, face_classifier returns and empty tuple
if faces is ():
    print("No faces found")

# We iterate through our faces array and draw a rectangle
# over each face in faces
for (x,y,w,h) in faces:
    cv2.rectangle(image, (x,y), (x+w,y+h), (127,0,255), 2)
    cv2.imshow('Face Detection', image)
    cv2.waitKey(0)
    
cv2.destroyAllWindows()

<>:17: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:17: SyntaxWarning: "is" with a literal. Did you mean "=="?
<ipython-input-2-691fdfd745aa>:17: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


In [1]:
import numpy as np
import cv2
 
face_classifier = cv2.CascadeClassifier('C:\\Users\\hp\\Desktop\\haarcascade_frontalface_default.xml')
eye_classifier = cv2.CascadeClassifier('‪C:\\Users\\hp\\Desktop\\haarcascade_eye.xml')
 
img = cv2.imread('C:\\Users\\hp\\Desktop\\Modi.jpg',1)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

faces = face_classifier.detectMultiScale(gray, 1.3, 5)

# When no faces detected, face_classifier returns and empty tuple
if faces is ():
    print("No Face Found")

for (x,y,w,h) in faces:
    cv2.rectangle(img,(x,y),(x+w,y+h),(127,0,255),2)
    cv2.imshow('img',img)
    cv2.waitKey(0)
    roi_gray = gray[y:y+h, x:x+w]
    print(roi_gray)
    roi_color = img[y:y+h, x:x+w]
    print(roi_color)
    eyes = eye_classifier.detectMultiScale(roi_gray)
    print(eyes)
    for (ex,ey,ew,eh) in eyes:
        cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(255,255,0),2)
        cv2.imshow('img',img)
        cv2.waitKey(0)
cv2.destroyAllWindows()

<>:13: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:13: SyntaxWarning: "is" with a literal. Did you mean "=="?
<ipython-input-1-51bf7714a9d1>:13: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


[[245 243 243 ... 255 255 255]
 [243 241 237 ... 255 255 255]
 [241 241 237 ... 255 255 255]
 ...
 [101 111  96 ... 255 255 255]
 [ 89 102  89 ... 255 255 255]
 [ 90  91  74 ... 255 255 255]]
[[[127   0 255]
  [127   0 255]
  [127   0 255]
  ...
  [127   0 255]
  [127   0 255]
  [127   0 255]]

 [[127   0 255]
  [127   0 255]
  [127   0 255]
  ...
  [127   0 255]
  [127   0 255]
  [127   0 255]]

 [[127   0 255]
  [127   0 255]
  [233 236 240]
  ...
  [255 255 255]
  [255 255 255]
  [127   0 255]]

 ...

 [[127   0 255]
  [127   0 255]
  [ 53  91 123]
  ...
  [255 255 255]
  [255 255 255]
  [127   0 255]]

 [[127   0 255]
  [127   0 255]
  [ 48  83 116]
  ...
  [255 255 255]
  [255 255 255]
  [127   0 255]]

 [[127   0 255]
  [127   0 255]
  [127   0 255]
  ...
  [127   0 255]
  [127   0 255]
  [127   0 255]]]


error: OpenCV(4.0.1) C:\ci\opencv-suite_1573470242804\work\modules\objdetect\src\cascadedetect.cpp:1658: error: (-215:Assertion failed) !empty() in function 'cv::CascadeClassifier::detectMultiScale'
